### ISSUE TITLE
Filetype set as html if it contains <!DOCTYPE html>

### ISSUE THREAD

**Issue by caneta** [andreshazard/vim-freemarker#1]
Hi @andreshazard!
I have the following problem: when I open a file with extension **.ftl** (directly from terminal or searching for it with netrw) its filetype is not recognized as freemarker, but as html.
I have to force it typing `:set filetype=freemarker` and then I get the correct syntax highlight.
Have you got any idea on how to solve this?
Thank you!

**Comment by andreshazard** [comment]
Hi @caneta 
I'm not able to reproduce the issue. The file type detection should be working for **.ftl** files.
- I've notice that you don't have your dotfiles on a repository, could you please show me your vimrc file ? 
  Maybe there is something overloading the file type detection. 
- What does :filetype display when your are editing a file? (Should say that detection plugin & indent are all ON.)
- Do you have a filetype.vim file on your .vim folder ? 

You can use this http://superuser.com/questions/68226/filetype-detection-not-working to troubleshoot as well. 

I'll be waiting for your feedback.

**Comment by caneta** [comment]
First of all I have to say that I'm not using Vim, but [Neovim](https://github.com/neovim/neovim) on an Ubuntu 12.04.
- My configuration files can be found [here](https://github.com/caneta/neovim_notes/tree/master/conf/real). I've got several plugins installed, I don't know if something overwrite filetype recognition.
- opening an .ftl file`:filetype` command gives to me `filetype detection:ON  plugin:ON  indent:ON`
- I have no filetype.vim inside `~/.config/nvim/` folder (which is the analogue of `.vim/` for Neovim)

Any ideas?

**Comment by andreshazard** [comment]
@caneta 

I don't have much experience with Neovim. I don't see anything particular on your config that could be causing the issue. I see that there is a filetype file, but it doesn't seem to be overriding the ftl settings.
I'll do some research and see if I can find anything. 

Maybe you could try with a "clean" Neovim config, just with this plugin to see if it's a Neovim issue or if it's something on your configuration. 

Thanks

**Comment by caneta** [comment]
I'm not a Neovim expert too, but I found that for basic configuration it has nothing different from Vim.

Anyway, here you are are my test:
- I've uninstalled every plugin, except vim-freemarker (with [vim-plug](https://github.com/junegunn/vim-plug) is really easy)
- I've created a temporary config file, _~/.config/nvim/init.tmp.vim_, with the following content only:

```
syntax on

call plug#begin('~/.config/nvim/plugins')
Plug 'andreshazard/vim-freemarker'
call plug#end()
```
- I've run neovim with that config file, opening an ftl file

```
nvim -u ~/.config/nvim/init.tmp.vim portal_normal.ftl
```

But I still get problems reported above: `:filetype` gives `filetype detection:ON plugin:ON indent:ON` and the file is recognized as HTML.

**Comment by andreshazard** [comment]
sorry to hear that @caneta 
I'm not sure what could be causing the issue. 

If you see here https://asciinema.org/a/6rhvlgcifjh3tjld0mhy67yhe you can see that I did a similar test and when I do :set filetype? a get "freemarker" as a result. This is how you are confirming the filetype is recognize has HTML right ? if not could you please run the same test that I ran on the video ?

**Comment by caneta** [comment]
[Here my test video](https://asciinema.org/a/d84q5nh0kcm6lf8d66hfa7o1t).
As you can see, opening a new buffer not yet saved on disk like _test.ftl_ the filetype is recognized.
But when I open an already existent file like _portlal_normal.ftl_, filetype is recognized as html.
I'm posting the position of your plugin inside neovim dirs, maybe a path issue?

```
candini@candubuntu:/home/candini$ tree ~/.config/nvim
/home/candini/.config/nvim
├── autoload
│   └── plug.vim
├── init.tmp.vim
└── plugins
    └── vim-freemarker
        ├── doc
        │   ├── freemarker.txt
        │   └── tags
        ├── ftdetect
        │   └── freemarker.vim
        ├── ftplugin
        │   └── freemarker.vim
        ├── README.md
        └── syntax
            └── freemarker.vim
```

**Comment by andreshazard** [comment]
@caneta 
- If you save the test.ftl file and then open it again, what filetype gets assigned ? 
- I installed neovim on my machine, after that I immediately opened an existent .ftl file and no filetype 
  was assigned, so I'm guessing there is still something on your config. 
- I was reading the neovim docs, and there is a filetype-overrule you could use but I didn't get how to use it. https://neovim.io/doc/user/filetype.html#filetype. Maybe what you could try is creating a "ftdetect" folder on your config _~/.config/nvim/ftdetect_ and copy the file from the plugin _vim-freemarker/frdetect/freemarker.vim_ into that folder. You can see that on the link above as well. 

Let me me know how it goes. Sorry I'm not able to help more =/

**Comment by caneta** [comment]
- I discovered that it changes behaviour depending on what you put inside the file.
  - If I save the file empty, when I reopen it, it works: filetype recognized is freemarker.
  - If I put inside test.ftl only the line `<!DOCTYPE html>` (which is the first line of my portal_normal.ftl tested above), filetype returns HTML. If I remove that line, close nvim and reopen it on the same file, now filetype is freemarker.

Indeed, in documentation you linked there is reported the following:

```
Vim can detect the type of file that is edited.  This is done by checking the
file name and sometimes by inspecting the contents of the file for specific
text.
```

Is that possible that your plugin don't overwrite filetype if Vim determine it by reading inside file opened?
- I've already make this test before and it didn't work

You helped a lot, don't worry! ;-D

**Comment by andreshazard** [comment]
@caneta 

Awesome, thanks for the info. 
I was able to reproduce this as well. 

If you add 
`autocmd BufNewFile,BufRead *.ftl set ft=freemarker`
to your vimrc the doctype will be ignore. 

I will investigate how can I add this to the plugin

**Comment by andreshazard** [comment]
@caneta 

I added a fix on the last commit. 
If you update the branch you should see it working. 

Thanks for the help.

**Comment by caneta** [comment]
Yeah, it works!
Now opening my _portal_normal.ftl_ it is recognized as filetype freemarker.
Thank you!
