### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by allcentury** [andreshazard/vim-freemarker#2]
Is there any plan to support indentation? Right now, autoindent(`gg=G` for me) moves everything to the same column space.

**Comment by andreshazard** [comment]
Thanks for bringing that up @allcentury 
I'll investigate how to incorporate that as soon as I have time.

**Comment by allcentury** [comment]
Thank you for the plugin!

**Comment by andreshazard** [comment]
This was implemented by the last update
